global:
  scrape_interval: "10s"
  evaluation_interval: "10s"

scrape_configs:
  - job_name: 'node_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo-exporter:9216']
